"""Contract tests for the strict Gate-0 quick analyzer."""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts")); sys.path.insert(0, str(ROOT / "src"))
import analyze_oracle_local_model_transfer_quick as analyzer  # noqa: E402
import run_oracle_local_model_transfer_quick as runner  # noqa: E402
from region_guided_reranking_study.local_surrogate_transfer_research import evaluate_predictions  # noqa: E402

SEEDS = [11, 23, 37, 53, 71, 89, 107, 131]
RELATIONS = ["identity", "output_affine", "scale_0.7", "scale_1.5", "rotate_45", "roughness", "reversal", "independent_expert"]
METHODS = ["Target-Only", "Geometry-Prior+Residual", "Oracle-Rank+Residual", "Oracle-Value+Residual", "Oracle-Rank+Value+Residual"]
SHELLS = [0.35, 0.7, 1.0]


def _fixture(tmp_path: Path) -> Path:
    # Keep fixtures generated by the current runner so audit and analyzer tests
    # exercise the exact persisted config, manifest, diagnostics and NPZ schema.
    d = tmp_path / "oracle_local_model_transfer_quick"
    runner.run_quick(runner.CANONICAL_CONFIG, d)
    return d


def test_analyzer_writes_required_outputs_and_contrasts_both_baselines(tmp_path: Path) -> None:
    d = _fixture(tmp_path); result = analyzer.run_analysis(d); out = d / "analysis"
    assert (out / "summary.csv").exists() and (out / "contrasts.csv").exists() and len(list(out.glob("*.png"))) == 3
    assert result["decision"]["quick_informal"] is True
    contrasts = pd.read_csv(out / "contrasts.csv")
    assert set(contrasts["baseline"]) == {"geometry", "target_only"}
    assert set(contrasts["metric"]) >= set(analyzer.DECISION_METRICS)


def _decision_for_results_frame(frame: pd.DataFrame) -> dict:
    results = analyzer._normalise_results(frame)
    return analyzer.decide(results, analyzer._contrasts(results))[1]


def test_exact_cartesian_validation_rejects_missing_cell(tmp_path: Path) -> None:
    d = _fixture(tmp_path)
    frame = pd.read_csv(d / "results.csv").iloc[1:].copy()
    decision = _decision_for_results_frame(frame)
    validation = decision["input_validation"]
    assert not validation["passes"]
    assert validation["n_rows"] == 1079
    assert validation["n_expected_cells"] == 1080
    assert validation["missing_cells"]


def test_exact_cartesian_validation_rejects_duplicate_cell(tmp_path: Path) -> None:
    d = _fixture(tmp_path)
    frame = pd.read_csv(d / "results.csv")
    frame = pd.concat([frame, frame.iloc[[0]]], ignore_index=True)
    decision = _decision_for_results_frame(frame)
    validation = decision["input_validation"]
    assert not validation["passes"]
    assert validation["n_rows"] == 1081
    assert validation["duplicate_cells"]


def test_exact_cartesian_validation_rejects_wrong_seed(tmp_path: Path) -> None:
    d = _fixture(tmp_path)
    frame = pd.read_csv(d / "results.csv")
    frame.loc[0, "seed"] = 999
    decision = _decision_for_results_frame(frame)
    validation = decision["input_validation"]
    assert not validation["passes"]
    assert 999 in validation["seeds"]
    assert any("seeds=" in failure for failure in validation["failures"])


def test_exact_cartesian_validation_rejects_missing_method_cell(tmp_path: Path) -> None:
    d = _fixture(tmp_path)
    frame = pd.read_csv(d / "results.csv")
    first = frame.iloc[0]
    mask = (frame.dimension == first.dimension) & (frame.panel == first.panel) & (frame.seed == first.seed) & (frame.relation_or_control == first.relation_or_control) & (frame.shell == first.shell) & (frame.method == "Oracle-Rank+Residual")
    frame = frame.loc[~mask].copy()
    decision = _decision_for_results_frame(frame)
    validation = decision["input_validation"]
    assert not validation["passes"]
    assert validation["missing_cells"]
    assert any("n_rows=" in failure for failure in validation["failures"])


def test_analysis_manifest_contains_finalized_source_and_output_hashes(tmp_path: Path) -> None:
    d = _fixture(tmp_path)
    analyzer.run_analysis(d)
    out = d / "analysis"
    manifest_path = out / "analysis_manifest.json"
    assert manifest_path.exists()
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert manifest["analyzer"]["sha256"] == hashlib.sha256(Path(analyzer.__file__).read_bytes()).hexdigest()
    for name in ("results.csv", "prediction_ledger.csv", "source_expert_diagnostics.csv", "config.json", "run_manifest.json"):
        assert manifest["source_inputs"][name]["sha256"] == hashlib.sha256((d / name).read_bytes()).hexdigest()
    output_names = ("summary.csv", "contrasts.csv", "relation_shell_headroom.png", "rank_value_dual_vs_geometry.png", "identity_observed_vs_permuted.png", "decision.json")
    for name in output_names:
        assert manifest["outputs"][name]["sha256"] == hashlib.sha256((out / name).read_bytes()).hexdigest()
    conclusion = d / "ORACLE_LOCAL_MODEL_TRANSFER_QUICK_CONCLUSION_CN.md"
    assert manifest["conclusion"]["sha256"] == hashlib.sha256(conclusion.read_bytes()).hexdigest()
    assert "analysis_manifest.json" not in manifest["outputs"]


def test_decision_has_explicit_strict_rules_and_never_uses_srmse(tmp_path: Path) -> None:
    d = _fixture(tmp_path); decision = analyzer.run_analysis(d)["decision"]
    assert set(decision["label"]) <= set("promising_rank_transferpromising_value_or_dual_head_transferno_oracle_headroom_stop_before_alignment")
    assert decision["rules"]["decision_metrics"] == list(analyzer.DECISION_METRICS)
    assert decision["rules"]["srmse_role"].startswith("secondary")
    assert decision["rules"]["positive_relations"] == list(analyzer.POSITIVE_RELATIONS)
    assert "head_to_head_evaluations" in decision
    assert "head_increment_rule" in decision["rules"]


def _set_gate_metrics(d: Path, rank_gain: float, value_extra: float = 0.0, dual_extra: float = 0.0) -> None:
    """Make a compact deterministic Geometry/Rank/Value fixture in raw results."""
    p = d / "results.csv"
    frame = pd.read_csv(p)
    positive = frame["relation_or_control"].isin(analyzer.POSITIVE_RELATIONS)
    permuted = frame["relation_or_control"].eq("identity_label_permutation")
    negative = frame["relation_or_control"].isin(analyzer.NEGATIVE_RELATIONS)
    for metric in analyzer.DECISION_METRICS:
        # Higher is better for the first two metrics.  Regret is lower better,
        # so reducing it by the same amount yields the same oriented delta.
        base = 0.5
        frame.loc[:, metric] = base
        gain = rank_gain
        rank = frame.method.eq("Oracle-Rank+Residual")
        value = frame.method.eq("Oracle-Value+Residual")
        dual = frame.method.eq("Oracle-Rank+Value+Residual")
        frame.loc[positive & rank, metric] = base + gain
        frame.loc[positive & value, metric] = base + gain + value_extra
        frame.loc[positive & dual, metric] = base + gain + dual_extra
        # Identity/permutation is the negative control for the identity rule.
        frame.loc[permuted & (rank | value | dual), metric] = base
        # Do not let negative conditions look like positive transfer.
        frame.loc[negative & (rank | value | dual), metric] = base - rank_gain
        if metric == "normalized_top1_regret":
            # Convert the values above into lower-is-better regret values while
            # retaining the desired oriented deltas.
            frame.loc[positive & rank, metric] = base - gain
            frame.loc[positive & value, metric] = base - gain - value_extra
            frame.loc[positive & dual, metric] = base - gain - dual_extra
            frame.loc[permuted & (rank | value | dual), metric] = base
            frame.loc[negative & (rank | value | dual), metric] = base + rank_gain
    frame.to_csv(p, index=False)


def _decision_from_mutated_fixture(tmp_path: Path, rank_gain: float, value_extra: float = 0.0, dual_extra: float = 0.0) -> dict:
    d = _fixture(tmp_path)
    _set_gate_metrics(d, rank_gain, value_extra, dual_extra)
    results = analyzer._normalise_results(pd.read_csv(d / "results.csv"))
    contrasts = analyzer._contrasts(results)
    return analyzer.decide(results, contrasts)[1]


def test_rank_only_legacy_data_does_not_select_equal_value_or_dual(tmp_path: Path) -> None:
    decision = _decision_from_mutated_fixture(tmp_path, rank_gain=.1)
    assert decision["label"] == "promising_rank_transfer"
    assert decision["selected_head"] == "rank"
    assert decision["head_evaluations"]["rank"]["passes"]
    assert not decision["head_to_head_evaluations"]["value"]["passes"]
    assert not decision["head_to_head_evaluations"]["dual"]["passes"]


def test_value_increment_beyond_rank_is_selected(tmp_path: Path) -> None:
    decision = _decision_from_mutated_fixture(tmp_path, rank_gain=.1, value_extra=.05)
    value = decision["head_to_head_evaluations"]["value"]
    assert decision["label"] == "promising_value_or_dual_head_transfer"
    assert decision["selected_head"] == "value"
    assert value["passes"]
    assert value["metric_detail"]["pairwise_accuracy"]["pair_wins"] == 96
    assert value["metric_detail"]["pairwise_accuracy"]["pair_ties"] == 0


def test_dual_increment_is_eligible_when_value_is_not(tmp_path: Path) -> None:
    decision = _decision_from_mutated_fixture(tmp_path, rank_gain=.1, dual_extra=.05)
    assert decision["label"] == "promising_value_or_dual_head_transfer"
    assert decision["selected_head"] == "dual"
    assert not decision["head_to_head_evaluations"]["value"]["passes"]
    assert decision["head_to_head_evaluations"]["dual"]["passes"]


def test_no_geometry_head_pass_stops(tmp_path: Path) -> None:
    decision = _decision_from_mutated_fixture(tmp_path, rank_gain=0.0)
    assert decision["label"] == "no_oracle_headroom_stop_before_alignment"
    assert decision["selected_head"] is None


def test_bootstrap_seed_uses_minimum_delta_for_win_rate() -> None:
    frame = pd.DataFrame({"seed": [1, 2, 3], "delta": [.05, .15, .25]})
    estimate, _low, _high, win_rate, n_seed = analyzer.bootstrap_seed(frame, n=200, minimum_delta=.1)
    assert np.isclose(estimate, .15)
    assert np.isclose(win_rate, 2 / 3)
    assert n_seed == 3


def test_missing_shell_is_decision_failure(tmp_path: Path) -> None:
    d = _fixture(tmp_path)
    frame = pd.read_csv(d / "results.csv")
    frame = frame[frame.shell != .35]
    frame.to_csv(d / "results.csv", index=False)
    results = analyzer._normalise_results(frame)
    label, decision = analyzer.decide(results, analyzer._contrasts(results))
    assert label == "no_oracle_headroom_stop_before_alignment"
    assert decision["selected_head"] is None
    assert not decision["input_validation"]["passes"]
    assert any("shells=" in failure for failure in decision["input_validation"]["failures"])


def test_negative_controls_decide_per_condition_not_pooled(tmp_path: Path) -> None:
    d = _fixture(tmp_path)
    frame = pd.read_csv(d / "results.csv")
    # Make one metric positive in each of three distinct conditions. Pooling
    # these rows would falsely replicate two metrics, but no condition reaches
    # the required 2/3 metric threshold.
    for metric, condition in zip(analyzer.DECISION_METRICS, analyzer.NEGATIVE_RELATIONS):
        mask = frame.relation_or_control.eq(condition) & frame.method.eq("Oracle-Rank+Residual")
        frame.loc[mask, metric] += .2 if metric != "normalized_top1_regret" else -.2
    frame.to_csv(d / "results.csv", index=False)
    results = analyzer._normalise_results(frame)
    decision = analyzer.decide(results, analyzer._contrasts(results))[1]
    ev = decision["head_evaluations"]["rank"]
    assert ev["negative_conditions_replicating"] == 0
    assert ev["negative_rule_pass"]
    assert all(detail["metrics_replicating"] == 1 for detail in ev["negative_condition_detail"].values())


def test_challenger_requires_rank_prerequisite(tmp_path: Path) -> None:
    d = _fixture(tmp_path)
    _set_gate_metrics(d, rank_gain=0.0, value_extra=.3, dual_extra=.3)
    results = analyzer._normalise_results(pd.read_csv(d / "results.csv"))
    decision = analyzer.decide(results, analyzer._contrasts(results))[1]
    assert not decision["head_evaluations"]["rank"]["passes"]
    assert decision["selected_head"] is None


def test_value_wins_exact_value_dual_tie(tmp_path: Path) -> None:
    decision = _decision_from_mutated_fixture(tmp_path, rank_gain=.1, value_extra=.05, dual_extra=.05)
    assert decision["selected_head"] == "value"
    assert decision["rules"]["selection_rule"].endswith("Never sum or mix metric values.")


def test_dimension_and_panel_keys_are_decision_safe(tmp_path: Path) -> None:
    d = _fixture(tmp_path)
    frame = pd.read_csv(d / "results.csv")
    frame.loc[frame.index[0], "dimension"] = 3
    frame.to_csv(d / "results.csv", index=False)
    results = analyzer._normalise_results(frame)
    _label, decision = analyzer.decide(results, analyzer._contrasts(results))
    assert not decision["input_validation"]["passes"]
    assert any("dimensions=" in failure for failure in decision["input_validation"]["failures"])

    frame = pd.read_csv(d / "results.csv")
    frame["dimension"] = 2
    frame.loc[frame.index[0], "panel"] = "train"
    frame.to_csv(d / "results.csv", index=False)
    results = analyzer._normalise_results(frame)
    _label, decision = analyzer.decide(results, analyzer._contrasts(results))
    assert not decision["input_validation"]["passes"]
    assert any("panels=" in failure for failure in decision["input_validation"]["failures"])
